{
  "swagger": "2.0",
  "info": {
    "title": "Coinbase API",
    "description": "The Coinbase v2 API",
    "version": "2.0.0",
    "contact": {
      "name": "CoinFabrik",
      "url": "http://www.coinfabrik.com/"
    }
  },
  "host": "api.coinbase.com",
  "schemes": ["https"],
  "basePath": "/v2",
  "security": [
    {
      "coinbaseAccessCode": []
    }
  ],
  "paths": {
    "/users/{user_id}": {
      "get": {
        "summary": "Retrieve User Information",
        "description": "This endpoint allows you to fetch detailed public information about any user by their unique user ID. It is particularly useful for applications that need to display or process user profiles based on their IDs. The response includes a comprehensive dataset containing user attributes as defined in the User schema. This is a read-only operation and does not expose sensitive or private user information.\n\n### Use Cases:\n- Fetching user data for profile display.\n- Verifyin[...]",
        "security": [
          {
            "coinbaseAccessCode": []
          }
        ],
        "tags": ["Users"]
      }
    },
    "/user": {
      "get": {
        "summary": "Retrieve Current User Information",
        "description": "This endpoint fetches public details about the currently authenticated user. To access sensitive or private information, such as the user's email address or other private attributes, additional permissions `wallet:user:email` and `wallet:user:read` must be included in the authentication scope.\n\n### Use Cases:\n- Retrieve basic public profile data for the authenticated user.\n- Validate the currently logged-in user's identity and display profile-related details.\n\n### K[...]",
        "security": [
          {
            "coinbaseAccessCode": []
          }
        ],
        "tags": ["Users"]
      },
      "put": {
        "summary": "Update Current User Preferences",
        "description": "This endpoint allows modification of the currently authenticated user's profile details and preferences. Users can update their name, time zone, and preferred native currency, among other customizable settings. It requires the `wallet:user:update` scope in the authentication token.\n\n### Use Cases:\n- Update user preferences such as time zone or currency for better localization.\n- Modify profile details such as the user’s name.\n\n### Key Features:\n- Requires `wallet:u[...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:user:update"]
          }
        ],
        "tags": ["Users"]
      }
    },
    "/user/auth": {
      "get": {
        "summary": "Retrieve Authorization Information",
        "description": "This endpoint retrieves the current user's OAuth2 authorization information, including the granted scopes and associated metadata such as send limits. It helps developers and users understand what permissions have been granted and the access level of the authenticated token.\n\n### Use Cases:\n- Determine which OAuth2 scopes have been granted to the authenticated user.\n- View metadata related to the user's authorization, such as send limits or other restrictions.\n- Vali[...]",
        "security": [
          {
            "coinbaseAccessCode": []
          }
        ],
        "tags": ["Users"]
      }
    },
    "/accounts": {
      "get": {
        "summary": "Retrieve a List of Accounts",
        "description": "This endpoint retrieves a list of all accounts associated with the currently authenticated user that the authorization method has access to.\n\n### Use Cases:\n- View all accounts linked to the authenticated user, including wallets, vaults, or other account types.\n- Fetch account details for further interactions, such as initiating transactions or checking balances.\n\n### Key Features:\n- Provides account data with pagination support for large datasets.\n- Requires the [...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:accounts:read"]
          }
        ],
        "tags": ["Accounts"]
      },
      "post": {
        "summary": "Create a New Account",
        "description": "This endpoint allows the creation of a new account for the authenticated user. The account can represent a wallet, vault, or other custom-defined entity.\n\n### Use Cases:\n- Create a new wallet or account for storing cryptocurrencies.\n- Set up a vault account for enhanced security.\n- Add a custom-named account for organizing user holdings.\n\n### Key Features:\n- Requires the `wallet:accounts:create` permission to access this functionality.\n- Allows the user to specif[...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:accounts:create"]
          }
        ],
        "tags": ["Accounts"]
      }
    },
    "/accounts/{account_id}": {
      "get": {
        "summary": "Retrieve Account Details",
        "description": "Fetch detailed information for a specific account associated with the authenticated user. You can also use the keyword `primary` instead of the `account_id` in the URL to access the user's primary account.\n\n### Use Cases:\n- Retrieve details of a specific account to check its status, balance, or other metadata.\n- Access the primary account without needing its specific `account_id`.\n\n### Key Features:\n- Provides account data including its type, balance, and other rel[...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:accounts:read"]
          }
        ],
        "tags": ["Accounts"]
      },
      "put": {
        "summary": "Update Account Name",
        "description": "Update the name of a specific account associated with the authenticated user.\n\n### Use Cases:\n- Modify the account name to reflect a new purpose or usage.\n- Update account metadata for better organization.\n\n### Key Features:\n- Allows changing the account name through a simple request.\n- Requires the `wallet:accounts:update` permission.\n\n### Important Notes:\n- Ensure the `account_id` is correctly formatted in the URL path.\n- The request body should include the [...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:accounts:update"]
          }
        ],
        "tags": ["Accounts"]
      },
      "delete": {
        "summary": "Delete an Account",
        "description": "Permanently delete a specified account associated with the authenticated user.\n\n### Use Cases:\n- Remove an inactive or redundant account.\n- Streamline account management by deleting unused accounts.\n\n### Key Features:\n- Enforces strict rules to prevent accidental deletion of critical accounts.\n- Requires the `wallet:accounts:delete` permission.\n\n### Important Notes:\n- The account cannot be deleted if it is:\n  - The primary account.\n  - An account with a non-z[...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:accounts:delete"]
          }
        ],
        "tags": ["Accounts"]
      }
    },
    "/accounts/{account_id}/primary": {
      "get": {
        "summary": "Set an Account as Primary",
        "description": "Promote a specified account to be the primary account for the authenticated user.\n\n### Use Cases:\n- Designate a new primary account for managing transactions.\n- Update the primary account when an old one becomes inactive or less frequently used.\n\n### Key Features:\n- Ensures that the specified account is set as the default account for the user.\n- Provides a seamless way to prioritize accounts based on user preferences.\n\n### Important Notes:\n- Requires the `walle[...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:accounts:update"]
          }
        ],
        "tags": ["Accounts"]
      }
    },
    "/accounts/{account_id}/addresses": {
      "get": {
        "summary": "List Addresses for an Account",
        "description": "Retrieves a list of addresses associated with the specified account. Addresses are used to receive funds and should be treated as single-use only to ensure optimal security and traceability.\n\n### Key Features:\n- Lists all addresses linked to a specific account, including their details and metadata.\n- Includes pagination support for large address lists.\n\n### Important Notes:\n- Each address should be used for only one transaction to maintain privacy and enhance fund [...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:addresses:read"]
          }
        ],
        "tags": ["Addresses"]
      },
      "post": {
        "summary": "Create a New Address for an Account",
        "description": "Generates a new receiving address for the specified account. Addresses can be created for all account types, including fiat accounts. When used with fiat accounts, funds are received via Instant Exchange.\n\n### Key Features:\n- Allows the creation of new receive addresses on demand.\n- Supports adding an optional label for better address management.\n\n### Important Notes:\n- If no additional properties are provided, a generic address is created.\n- Addresses are generat[...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:addresses:create"]
          }
        ],
        "tags": ["Addresses"]
      }
    },
    "/accounts/{account_id}/addresses/{address_id}": {
      "get": {
        "summary": "Retrieve Details for a Specific Address",
        "description": "Fetches details of a specific address associated with a particular account. Addresses are unique identifiers used for receiving cryptocurrency transactions. Regular Bitcoin addresses can also be used in place of the `address_id`, provided the address is linked to the specified account.\n\n### Key Features:\n- Returns metadata and details about a single address.\n- Supports querying using the `address_id` or an actual cryptocurrency address (e.g., Bitcoin address) linked t[...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:addresses:read"]
          }
        ],
        "tags": ["Addresses"]
      }
    },
    "/accounts/{account_id}/addresses/{address_id}/transactions": {
      "get": {
        "summary": "Retrieve Transactions for a Specific Address",
        "description": "Fetches the list of all transactions associated with a particular cryptocurrency address within a specific account. Transactions include details of funds sent to or received by the address.\n\n### Key Features:\n- Lists all transactions tied to the specified address.\n- Supports querying using either the `address_id` or a valid cryptocurrency address (e.g., Bitcoin address), provided it is linked to the specified account.\n\n### Important Notes:\n- Ensure the `address_id`[...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:transactions:read"]
          }
        ],
        "tags": ["Addresses"]
      }
    },
    "/accounts/{account_id}/transactions": {
      "get": {
        "summary": "Retrieve Transactions for an Account",
        "description": "Fetches a list of all transactions associated with the specified account. Transactions include both incoming and outgoing payments, along with relevant metadata.\n\n### Key Features:\n- Lists all account transactions with pagination support.\n- Provides transaction details such as amounts, timestamps, and transaction statuses.\n- Useful for auditing account activity and generating transaction histories.\n\n### Example Use Cases:\n- View all transactions associated with a [...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:transactions:read"]
          }
        ],
        "tags": ["Transactions"]
      },
      "post": {
        "summary": "Send or Request Money",
        "description": "Allows users to either send funds to a recipient or request funds from a sender. Transactions can be on-chain (blockchain) or off-chain (Coinbase's internal ledger).\n\n### Sending Funds (type=\"send\"):\n- Funds can be sent to a cryptocurrency address or email.\n- Fees are covered by Coinbase for larger transactions (≥0.0001 BTC) up to 25 per day.\n- Supports instant exchange for fiat-to-crypto transfers if the user has buying privileges.\n\n### Requesting Funds (type=\"[...]",
        "security": [
          {
            "coinbaseAccessCode": [
              "wallet:transactions:send",
              "wallet:transactions:request"
            ]
          }
        ],
        "tags": ["Transactions"]
      }
    },
    "/accounts/{account_id}/transactions/{transaction_id}": {
      "get": {
        "summary": "Retrieve Transaction Details",
        "description": "Fetches detailed information about a specific transaction associated with an account. This endpoint is useful for viewing the status, amount, recipient, and other metadata of a transaction.\n\n### Key Features:\n- Provides comprehensive details about a specific transaction.\n- Supports on-chain and off-chain transactions.\n- Useful for auditing or reviewing the details of a transaction.\n\n### Example Use Cases:\n- View the recipient and amount of a specific cryptocurrenc[...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:transactions:read"]
          }
        ],
        "tags": ["Transactions"]
      },
      "delete": {
        "summary": "Cancel Money Request",
        "description": "Allows a user to cancel a pending money request. Money requests can be canceled by either the sender or the recipient.\n\n### Key Features:\n- Cancels a money request before it is accepted.\n- Applicable for both senders and recipients of the request.\n- Does not apply to completed transactions or those already fulfilled.\n\n### Example Use Cases:\n- The recipient declines a money request, and the sender wants to cancel it.\n- A sender cancels an unfulfilled money request[...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:transactions:request"]
          }
        ],
        "tags": ["Transactions"]
      }
    },
    "/accounts/{account_id}/transactions/{transaction_id}/complete": {
      "post": {
        "summary": "Complete Money Request",
        "description": "Allows the recipient of a money request to complete the transaction by sending the requested amount to the user who initiated the request. This action can only be performed by the user to whom the money request was made. The user who sent the request cannot execute this endpoint.\n\n### Key Features:\n- Finalizes a pending money request by transferring funds to the requestor.\n- Ensures the transaction completes securely and only by the intended recipient.\n\n### Example [...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:transactions:request"]
          }
        ],
        "tags": ["Transactions"]
      }
    },
    "/accounts/{account_id}/transactions/{transaction_id}/resend": {
      "post": {
        "summary": "Resend Money Request",
        "description": "Allows the user to resend a pending money request to the recipient. This action sends a new notification email to the recipient, reminding them about the outstanding request.\n\n### Key Features:\n- Sends a fresh email notification to the recipient of the money request.\n- Can be used to remind recipients of unresolved or delayed money requests.\n\n### Example Use Cases:\n- A user wants to follow up on a pending money request by sending another notification.\n- Automates [...]",
        "security": [
          {
            "coinbaseAccessCode": ["wallet:transactions:request"]
          }
        ],
        "tags": ["Transactions"]
      }
    }
  },
  "securityDefinitions": {
    "coinbaseAccessCode": {
      "type": "oauth2",
      "scopes": {
        "wallet:accounts:read": "List user’s accounts and their balances",
        "wallet:accounts:update": "Update account (e.g. change name)",
        "wallet:accounts:create": "Create a new account (e.g. BTC wallet)",
        "wallet:accounts:delete": "Delete existing account",
        "wallet:addresses:read": "List account’s bitcoin addresses",
        "wallet:addresses:create": "Create new bitcoin addresses for wallets",
        "wallet:buys:read": "List account’s buys",
        "wallet:buys:create": "Buy bitcoin",
        "wallet:checkouts:read": "List user’s merchant checkouts",
        "wallet:checkouts:create": "Create a new merchant checkout",
        "wallet:deposits:read": "List account’s deposits",
        "wallet:deposits:create": "Create a new deposit",
        "wallet:notifications:read": "List user’s notifications",
        "wallet:orders:read": "List user’s merchant order",
        "wallet:orders:create": "Create a new merchant order",
        "wallet:orders:refund": "Refund a merchant order",
        "wallet:payment-methods:read": "List user’s payment methods (e.g. bank accounts)",
        "wallet:payment-methods:delete": "Remove existing payment methods",
        "wallet:payment-methods:limits": "Get detailed limits for payment methods (useful for performing buys and sells). This permission is to be used together with wallet:payment-methods:read",
        "wallet:sells:read": "List account’s sells",
        "wallet:sells:create": "Sell bitcoin",
        "wallet:transactions:read": "List account’s transactions",
        "wallet:transactions:send": "Send bitcoin",
        "wallet:transactions:request": "Request bitcoin from a Coinbase user",
        "wallet:transactions:transfer": "Transfer funds between user’s two bitcoin accounts",
        "wallet:user:read": "List detailed user information (public information is available without this permission)",
        "wallet:user:update": "Update current user",
        "wallet:user:email": "Read current user’s email address",
        "wallet:withdrawals:read": "List account’s withdrawals",
        "wallet:withdrawals:create": "Create a new withdrawal"
      },
      "flow": "accessCode",
      "authorizationUrl": "https://www.coinbase.com/oauth/authorize",
      "tokenUrl": "http://www.coinbase.com/oauth/token"
    }
  }
}
